import { generatorID } from "./generatorID"; 

export let clientesBD = [{
    id: generatorID(),
    nombre: "Botteri Joaquin",
    razonsocial: "Botteri SA",
    contacto: "Joaquin Botteri",
    telefono: 123456789,
    mail: "joaquin@mail.com",
},
{
    id: generatorID(),
    nombre: "Cangiani Marcelo",
    razonsocial: "Logistica Cangiani",
    contacto: "Cangiani Logistica",
    telefono: 987654321,
    mail: "marcelo@mail.com",
},
{
    id: generatorID(),
    nombre: "Morelli Ariel",
    razonsocial: "MAVI",
    contacto: "Ariel Morelli",
    telefono: 654987321,
    mail: "mavi@mail.com",
},
{
    id: generatorID(),
    nombre: "La bolita",
    razonsocial: "Marrones SA",
    contacto: "Carmen",
    telefono: 654321987,
    mail: "bolita@mail.com",
},
{
    id: generatorID(),
    nombre: "Gonzalez Maria",
    razonsocial: "Servicios Gonzalez",
    contacto: "Maria Gonzalez",
    telefono: 1122334455,
    mail: "maria@mail.com",
},
{
    id: generatorID(),
    nombre: "Perez Juan",
    razonsocial: "Perez & Asociados",
    contacto: "Juan Perez",
    telefono: 2233445566,
    mail: "juan@mail.com",
},
{
    id: generatorID(),
    nombre: "Lopez Carlos",
    razonsocial: "Construcciones Lopez",
    contacto: "Carlos Lopez",
    telefono: 3344556677,
    mail: "carlos@mail.com",
},
{
    id: generatorID(),
    nombre: "Martinez Ana",
    razonsocial: "Ana Martinez Estudio",
    contacto: "Ana Martinez",
    telefono: 4455667788,
    mail: "ana@mail.com",
},
{
    id: generatorID(),
    nombre: "Sanchez Luis",
    razonsocial: "Sanchez Servicios",
    contacto: "Luis Sanchez",
    telefono: 5566778899,
    mail: "luis@mail.com",
},
{
    id: generatorID(),
    nombre: "Garcia Laura",
    razonsocial: "Consultora Garcia",
    contacto: "Laura Garcia",
    telefono: 6677889900,
    mail: "laura@mail.com",
}
];
